from .arxiv_prompts import (
    OPENAI_ARXIV_API_PROMPT_TEMPLATE,
    OPENAI_ARXIV_API_SYSTEM_PROMPT,
    OPENAI_ARXIV_COMPARE_PROMPT_TEMPLATE,
    OPENAI_ARXIV_COMPARE_SYSTEM_PROMPT,
)

__all__ = [
    "OPENAI_ARXIV_API_SYSTEM_PROMPT",
    "OPENAI_ARXIV_API_PROMPT_TEMPLATE",
    "OPENAI_ARXIV_COMPARE_SYSTEM_PROMPT",
    "OPENAI_ARXIV_COMPARE_PROMPT_TEMPLATE",
]
